name: Scrape

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:  # for testing

# "ACTIONS_...": true is only required for Python on GitHub due to a bug.
# Unsure if this is fixed yet. Test and remove if able to.
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
#  DATE: ${{ env.DATE }}

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Set up environment
        run: |
          echo "DATE=$(date -u +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> $GITHUB_ENV
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> $GITHUB_ENV

      - name: Write Firebase credentials
        run: echo "$FIREBASE_SERVICE_ACCOUNT_IMMACULATE_PANEL" > .cert/firebase-cert.json
        env:
          FIREBASE_SERVICE_ACCOUNT_IMMACULATE_PANEL: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_IMMACULATE_PANEL }}

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install py packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Execute py script
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY}}
        working-directory: firebase/cms
        run: python scrape.py
      
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Scraping report for # ${{env.DATE}}
          to: ${{secrets.MAIL_USERNAME}}
          from: Automated Email
          ignore_cert: true
          secure: true
          html_body: |
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta http-equiv="X-UA-Compatible" content="IE=edge">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Scraping Report</title>
            </head>
            <body>
                <h2>Scraping Report</h2>
                <p>This is an automated scraping report for the date: <strong>${{ env.DATE }}</strong></p>
                
                <!-- Add more content as needed -->
      
                <p>Thank you!</p>
            </body>
            </html>